name: compile_release

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies and build
        run: |
          pip install .
          pip install pyinstaller
          python ./compiling/compile.py zipped
          
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-zip
          path: ./dist/*_win.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies and build
        run: |
          sudo apt-get update && sudo apt-get install -y libegl1-mesa
          pip install .
          pip install pyinstaller
          python ./compiling/compile.py zipped
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-gz
          path: ./dist/*_lnx.tar.gz

  create-release:
    permissions:
      contents: write
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: dist
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --title="$tag" \
            --draft \
            dist/windows-zip/*_win.zip \
            dist/linux-gz/*_lnx.tar.gz
        shell: bash