name: compile_release

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
      runs-on: ubuntu-latest

      permissions:
        contents: write

      steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
                  python-version: 3.x
          - name: Install system dependencies
            run: | 
              sudo apt-get update && sudo apt-get install -y libegl1-mesa
          - name: Install dependencies
            run: |
              pip install .
              pip install pyinstaller

          - name: Build plugin
            run: |
              python ./compiling/compile.py zipped
      
          - name: Create release
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              tag="${GITHUB_REF#refs/tags/}"
              filePath=$(ls ./dist/Measury_*.zip) # Adjust the pattern to match your file naming convention

              gh release create "$tag" \
                --title="$tag" \
                --draft \
                "$filePath"