name: Compile Project

on:
  push:
    tags:
      - "*"

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
                  python-version: 3.x
          - name: Install system dependencies
            run: | 
              sudo apt-get update && sudo apt-get install -y libegl1-mesa
              sudo apt-get install -y xvfb
          - name: Install dependencies
            run: |
              pip install .
              pip install pyinstaller

          - name: Build plugin
            run: |
              python ./compiling/compile.py
      
          - name: Create release
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              tag="${GITHUB_REF#refs/tags/}"
      
                gh release create "$tag" \
                  --title="$tag" \
                  --draft \
                  Measury-$tag.zip