name: pytests

on: 
  repository_dispatch:
    types: [pytests]
  push:
    branches:
      - dev
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies
      run: | 
        sudo apt-get update && sudo apt-get install -y libegl1-mesa
        sudo apt-get install -y xvfb
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install .
    - name: Test with pytest
      uses:  GabrielBB/xvfb-action@v1
      with:
        run: pytest ./tests/test_wo_gui.py